#!/usr/bin/env bash
# Script to transfer file to a server
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4
if [ $# -ne 4 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$FILE_PATH" -o StrictHostKeyChecking=no \
        "$FILE_PATH" "$USER"@"$IP":~/
fi
