#!/usr/bin/env bash
# Script to transfer file to a server
FILE_PATH=$1
IP=$2
USER=$3
SSH_KEY=$4
if [ $# -ne 4 ];
then
    echo "Usage: 0-transfer_file FILE_PATH IP USER SSH_KEY"
else
    scp -i "$FILE_PATH" -o StrictHostKeyChecking=no \
        "$FILE_PATH" "$USER"@"$IP":~/
fi
