#!/usr/bin/env bash
# install Nginx on a remote server

apt-get update
apt-get --yes install 'nginx'
mkdir --parents '/var/www/html'
echo 'Holberton School' > '/var/www/html/index.html'
service nginx reload
service nginx restart
