#!/usr/bin/env bash
# set up haproxy
sudo apt-get -y update
sudo apt-get -y install 'haproxy'
cat > '/etc/haproxy/haproxy.cfg' << EOF
frontend markhedgeland.tech
	bind *:80
	stats uri /haproxy?stats
	default_backend web_servers
backend web_servers
	balance roundrobin
	server web-01 34.73.165.22
	server web-02 34.73.177.149
EOF
service haproxy reload
service haproxy restart
