#!/usr/bin/env bash
# Print 'Hi' on 9th loop
COUNTER=0
while [  $COUNTER -lt 10  ];
do
    if [  $COUNTER = 9  ];
    then
        echo "Hi"
    fi
    echo "Holberton School"
    let COUNTER=COUNTER+1
done