#!/usr/bin/env bash
# Prints something different for '4' and '8'
COUNTER=1
while [  $COUNTER -lt 11  ];
do
    if [  $COUNTER = 4  ];
    then
        echo "bad luck"
    elif [  $COUNTER = 8  ];
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    let COUNTER=COUNTER+1
done